baseURL: https://gion.io
languageCode: en
title: gion . io
theme: hugo-theme-codex

defaultContentLanguage: en
hasCJKLanguage: false
enableRobotsTXT: false

copyright: Copyright © 2023 by Tobias Gion - All content is licensed under the BSD Zero Clause License.
pluralizeListTitles: false
enableGitInfo: true

params:
  dateFormat: 2 Jan 2006
  description: Your open source for privacy related topics, FreeBSD-based systems and computer security.    
  showPageTitleInTOC: false
 
markup:
  highlight:
    codeFences: true
    tabWidth: "8"
    lineAnchors: ""
    style: "xcode"

  goldmark:
    renderer:
      unsafe: false
      
# frontmatter:
#  date:
#    - date
#    - publishDate
#    - lastmod
#  lastmod:
#    - :git
#    - lastmod
#    - :fileModTime
  
menu:
  main:
    - identifier: home
      name: home
      title: home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      title: blog
      url: /blog/
      weight: 20
    - identifier: about
      name: about
      title: about . me
      url: /about/
      weight: 30
    - identifier: contact
      name: contact
      title: contact . me
      url: /contact/
      weight: 40
