name: Build and deploy Hugo site on gion.io
on: [push, workflow_dispatch]  
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      
      # Needed for .GitInfo variable .AuthorDate to work after deployment: git config --global core.quotepath false
      - name: Set up git
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends git
          git config --global core.quotepath false    
      
      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.111.3
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends hugo

      # Build Hugo site to subfolder htdocs 
      - name: Build
        run: hugo -d ${{ github.workspace }}/htdocs --minify

      # Need to install wireguard to access the server (ssh only allowed inside vpn)
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUB_KEY }}'
          ips: '${{ secrets.CLIENT_IP }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.CLIENT_PRV_KEY }}'
          preshared_key: '${{ secrets.CLIENT_PRE_KEY }}'
      
      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      
      # Deploy site from subfolder htdocs to webserver on gion.io
      - name: Deploy
        run: scp -r htdocs/* github@'${{ secrets.ENDPOINT_PRIVATE_IP }}':/usr/local/www/gionio
